version: 2.1

orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-then-deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      #--------------- INSTALL FRONTEND DEPENDENCIES ---------------#
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install

      #
      #--------------- BUILD FRONTEND ---------------#
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      #--------------- DEPLOY FRONTEND TO S3 ---------------#
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      #--------------- INSTALL BACKECND DEPENDENCIES ---------------#
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      #--------------- IN PACKAGE.JSON, CHANGE MAIN ENTRY ---------------#
      - run:
          name: Back-End Change Main Entry Point
          command: |
            npm run backend:change-main
        #--------------- BUILD BACKEND ---------------#
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
        #--------------- INSTALL AWS EB CLI ---------------#
      - run:
          name: Installing AWS Elasticbeanstalk
          command: |
            npm run backend:aws-eb
        #--------------- DEPLOY BACKEND TO EB ---------------#
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy

workflows:
  build-then-deploy:
    jobs:
      - build-then-deploy:
          context: aws
          filters:
            branches:
              only:
                - main
